### ISSUE TITLE
DeskPad output always looks blurry even when HiDPI resolution is selected

### ISSUE THREAD

**Issue by zliebersbach** [Stengo/DeskPad#18]
<img width="1000" alt="Screenshot 2023-11-16 at 12 56 04" src="https://github.com/Stengo/DeskPad/assets/13294419/d0ac8237-547f-43a2-bdcb-f3bc1c53569d">

**Comment by Stengo** [comment]
Nice catch! When HiDPI options were added in https://github.com/Stengo/DeskPad/pull/10, the stream resolution was not adjusted accordingly, so it ended up looking the same as the low DPI variant. This should be fixed by https://github.com/Stengo/DeskPad/commit/268581f8be7a0aaea86c6990e116ea7138c3521c and is now available in [Release v1.3](https://github.com/Stengo/DeskPad/releases/tag/v1.3)
